line-length = 100  # Set maximum line length
target-version = "py312"  # Target Python version

[lint]
select = ["E", "F"]  # Enable pycodestyle and Pyflakes rules
extend-select = ["B"]  # Add flake8-bugbear rules
ignore = ["B008", "E501"]

[lint.per-file-ignores]
"__init__.py" = ["F401"]  # Ignore unused imports in __init__.py
"tests/*" = ["E402"]  # Ignore import order in tests
